### ISSUE TITLE
How to load as library or add to project?

### ISSUE THREAD

**Issue by damesek** [xvinny/strict_variant#2]
Hi,

I tried several ways to add to my Arduino project, because I would like to use vector variants, but not work.. otherwise that could be really helpful.. for me.
Could you help me, how could I use this? Add to a project? 
Do I need to modify all headers' locations?

Many thanks,
Szabolcs

**Comment by xvinny-zz** [comment]
Hi Szabolcs,

If you are using Arduino IDE, you should clone the library, put into a subfolder in your project and reference the headers that you need (in your case, variant.hpp).
If you are using PlatformIO, you should add the strict_variant to platformio.ini file (under lib_deps).

Regards,

Vinicius

**Comment by damesek** [comment]
Hi xvinny,

Thanks, I solved with Arduino/Bridge add-on.

Regards,
Szabolcs
